DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  url VARCHAR(255) NOT NULL,
  price INTEGER  NOT NULL DEFAULT 0,
  cal INTEGER

);
