DROP TABLE IF EXISTS items_orders CASCADE;
CREATE TABLE items_orders(
  id SERIAL PRIMARY KEY NOT NULL,
  item_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  order_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  quantity INTEGER  NOT NULL DEFAULT 0

);
